### ISSUE TITLE
initialize fresh map.sqlite

### ISSUE THREAD

**Issue by ghost** [LeMagnesium/python-minetest#12]
to make it easier to do backups and for worlds where the map.sqlite is missing (ie, not working inside a world folder) it would be nice to be able to create the empty map.sqlite file from the library.

**Comment by Lymkwi** [comment]
Theorically it isn't complicated. The SQLite request is already in Minetest's source code, I just need to copy it. I'll try to do it right now.

**Comment by Lymkwi** [comment]
Is [that](https://github.com/LeMagnesium/python-minetest/commit/51c7f1bfa465ac87ce6ab8e15bfd44040458582b) enough for you?

**Comment by ghost** [comment]
i am using this feature so it is all good. thanks
